const mp4 = require('../app/assets/images/*.mp4');

export default {

  "steps": [
    {
      "id": 1,
      "background__1": "https://i.goopics.net/OKPj7.png",
      "title": "Igor Kostine",
      "profession": "Photographe",
      "texte__1": "Surnommé << l'Homme légendaire >> par le Washington Post, Igor Kostine est un témoin capital de la catastrophe de Tchernobyl. Le 26 avril 1986, quelques heures seulement après l'explosion, il survole la centrale.",
      "texte__2": "Surpris par l'ampleur de la catastrophe et par le silence des autorités, Igor Kostine décide de rester sur place et de vivre au milieu des 800 000 << liquidateurs >> qui se succéderont sur le site de l'accident.",
      "texte__3": "Lui-même irradié, il n'aura de cesse, vingt années durant, de photographier la centrale et la zone interdite qui l'entoure. Son histoire se confond avec celle de Tchernobyl. Il a vu l'évacuation des villages, le désespoir et le courage des populations, la construction du sarcophage, les hommes déplaçant à mains nues des blocs radioactifs, les cimetières de machines, les jardins et les vergers contaminés redevenus des terres sauvages où l'homme n'a plus sa place...",
      "background__2": "https://i.goopics.net/jv1my.png",
      "sentence__1": "<< Le soir, quand je développais la pellicule, je la trouvais mouchetée de tâches à cause de la radiation. >>",
      "sentence__2": "<< Igor, pour utiliser de manière plus efficace la main-d’œuvre, prends une photo panoramique du toit pour que les soldats l’étudient et sachent où exactement aller quand ils sortent de l’ascenseur afin qu’ils ne fassent pas de mouvements inutiles. >>",
      "sentence__3": "-Nikolaï Tarakanov",
      "sentence__4": ", Général de Division ayant mené l’operation de décontamination du toit.",
      "sentence__5": "<< À six heures du matin, nous avons embarqué dans un hélicoptère militaire à l’aide duquel les soldats devaient s’approcher du tuyau. >>",
      "background__3": "https://i.goopics.net/4vxj8.png",
      "sentence__6": "<< J’ai survolé 50 fois le réacteur numéro 4 en hélicoptère. J’ai pris des photos à toutes les étapes de la liquidation de cette catastrophe. J’ai photographié des gens descendant dans la mine, les soldats « liquidateurs » travaillant sur le toit de la centrale.” Personne n’avait jamais vu une chose pareille. >>",
      "sentence__7": "<< Au début, le Japon et l’Allemagne avaient envoyé des robots, mais à cause de l’irradiation, ils se sont bloqués. Je les ai photographiés depuis l’hélicoptère pendant qu’ils s’écroulaient. Après cela, des milliers de soldats ont dû nettoyer le graphite radioactif et le toit du troisième bloc de la centrale d’une surface de 250 mètres carrés. >>",
      "background__slider": "https://i.goopics.net/K8wm3.png",
      "image__slider": "https://i.goopics.net/VvmDV.png",
      "image__slider__2": "https://i.goopics.net/qvpGk.png",
      "image__slider__3": "https://i.goopics.net/kjVky.png",
      "image__slider__4": "https://i.goopics.net/aOjKZ.png",
      "image__slider__5": "https://i.goopics.net/gE1Ko.png",
      "video__1": mp4.igor,
      "video__2": mp4.outroIgor
    },
    {
      "id": 2,
      "background__1": "https://i.goopics.net/aOg1Z.png",
      "title": "Yuri Korneev",
      "profession": "Opérateur turbine de la centrale",
      "texte__1": "<< Au moment où la turbine a cessé de fonctionner, il y a eu une explosion soudaine dans la zone du corridor de la tuyauterie. Je l'ai vu de mes propres yeux, entendu de mes propres oreilles. J'ai vu des morceaux du mur en béton armé commencer à s'effriter et le toit en béton armé de notre Turbine 7 a commencé à tomber. >>",
      "background__2": "https://i.goopics.net/eQmA5.png",
      "sentence__2": "<< C'était tellement inattendu. Il était difficile de comprendre ce qui se passait. L'explosion et l'effondrement du toit n'ont pris qu'une minute, peut-être même moins. Immédiatement après, Boris Rogoshin, chef de quart, et l’ingénieur en chef adjoint (maintenant décédé) se sont précipités dans la salle des turbines depuis le centre de contrôle. On m'a ordonné de m'occuper de Turbine 8 et de ne faire attention à rien d'autre. >>",
      "background__3": "https://i.goopics.net/dR7EL.png",
      "sentence__6": "<< J'étais complètement dans le noir. . . Pendant que j'étais occupé avec la turbine, un électricien, Baranov - qui est décédé plus tard à l'hôpital de Moscou - s'est précipité et a commencé à pomper l'hydrogène qui a refroidi le générateur à turbine. Ses actions ont empeché une autre explosion. >>",
      "background__slider": "https://i.goopics.net/K8wm3.png",
      "image__slider": "https://i.goopics.net/dRXaO.png",
      "image__slider__2": "https://i.goopics.net/NvKQY.png",
      "image__slider__3": "https://i.goopics.net/kjrwb.png",
      "image__slider__4": "https://i.goopics.net/VvQbZ.png",
      "image__slider__5": "https://i.goopics.net/dRXaE.png",
      "video__1": mp4.yuri,
      "video__2": mp4.outroIgor
    },
    {
      "id": 3,
      "background__1": "https://i.goopics.net/WbQRk.png",
      "title": "Liquidateur",
      "texte__1": "<< Je suis un militaire..",
      "texte__2": "..Quand on me donne des ordres je dois obéir, mais il y avait tout de même un élan héroïque ",
      "texte__3": " Avant d'y aller j'avais peur. >>",
      "background__2": "https://i.goopics.net/kjr0l.png",
      "sentence__1": " Nous sommes entrés. Une pancarte annonçait défense d’entrer sous aucun prétexte.",
      "sentence__2": "Il existait un risque d’explosion nucléaire, pour l’éviter il a fallu vider le réservoir d’eaux lourdes pour que le réacteur ne s’écroule pas dedans.",
      "background__3": "https://i.goopics.net/D8vyX.png",
      "sentence__6": "Au total, 209 unités militaires ont étés envoyés pour liquider les conséquences de la catastrophe. ",
      "sentence__7": "Cela fait près de 340 000 hommes. Un véritable enfer pour ceux qui ont nettoyé le toit.",
      "sentence__8": "On leurs donnaient des tabliers en plomb, mais la radiation venait d’en bas, et là ils n’étaient pas protégés.",
      "sentence__9": "Ils passaient là-haut entre une minute trente et deux minutes par jours.",
      "sentence__10": "De jeunes gars. Ils sont en train de mourir actuellement.",
      "background__slider": "https://i.goopics.net/K8wm3.png",
      "image__slider": "https://i.goopics.net/vQlKg.png",
      "image__slider__2": "https://i.goopics.net/7qRmG.png",
      "image__slider__3": "https://i.goopics.net/AJjRa.png",
      "image__slider__4": "https://i.goopics.net/LQ0D8.png",
      "image__slider__5": "https://i.goopics.net/5q4m7.png",
      "video__1": mp4.liquidateur,
      "video__2": mp4.outroIgor
    },
    {
      "id": 4,
      "background__1": "https://i.goopics.net/3vWm8.png",
      "title": "Tatiana",
      "profession": "Petite fille de Pripyat",
      "texte__2": "Un ordre d'évacuation a été annoncé tôt dans la matinée du 27 avril. Biensûr, une évacuation temporaire. Ce mot temporaire a suffi pour créer une stupeur générale. L'évacuation est quelque chose qu'on ne voyait que dans les films de guerre.",
      "background__2": "https://i.goopics.net/aOQmA.png",
      "sentence__1": "Où devions-nous aller ? Pour combien de temps ? Où allions-nous vivre?",
      "sentence__2": "A midi, tout le monde est monté les bus et nous sommes partis. Quand nous avons rejoint le convoi général, les gens n'en revenaient pas. Une colonne infinie DE MILLIERS d'autobus s'étirait devant nous. Soudainement, nous avons pris conscience du sérieux de la situation.",
      "sentence__4": "A mon avis, l'évacuation de Pripyat était un exploit logistique. Je ne sais pas quand il a été décidé de déplacer les gens, mais les autorités avaient à peine plus d'une journée pour l'organisation de l'évacuation et le relogement de 48.000 habitants dans des villages de la région.",
      "background__3": "https://i.goopics.net/VvQY1.png",
      "sentence__6": "L'établissement était plein d'habitants de Pripyat. Au début, les médecins ont mesuré notre taux de radiation avec un dosimètre. Et puis on nous a annoncé les résultats : entre 50 et 600 microRoentgen selon les différentes parties du corps. Mais le problème c'est qu'ils ne savaient pas quelle était la norme.",
      "sentence__7": "A l'hôpital, nous avons été obligés de nous baigner tous les jours toutes les 90 minutes, de passer des tests et de prendre des poignées de vitamines. Les médecins m'ont coupé les cheveux parce qu'ils avaient absorbé toute la radioactivité contenue dans l'air de Pripyat. Après deux semaines, nous avons pu quitter l'hôpital.",
      "sentence__8": "Pour moi, le plus terrible est arrivé quelques mois plus tard, quand il est finalement apparu clairement que nous ne pourrions plus revenir à Pripyat. J'ai pleuré pendant deux jours, jusqu'à ce qu'on nous dise qu'on pourrait y retourner d'ici 30 ans.",
      "background__slider": "https://i.goopics.net/K8wm3.png",
      "image__slider": "https://i.goopics.net/vQlGg.png",
      "image__slider__2": "https://i.goopics.net/7qRWG.png",
      "image__slider__3": "https://i.goopics.net/AJjga.png",
      "image__slider__4": "https://i.goopics.net/LQ0P8.png",
      "image__slider__5": "https://i.goopics.net/5q4R7.png",
      "video__1": mp4.fillette,
      "video__2": mp4.outroIgor
    },
    {
      "id": 5,
      "background__1": "https://i.goopics.net/PDmg0.png",
      "title": "Anatoly Dyatlov",
      "profession": "Chef Ingénieur de la centrale",
      "texte__1": "<< On m’a évacué le premier jour. Le réacteur brulait. >>",
      "texte__2": "Le 26 avril 1986, il supervise les tests du réacteur 4 de la centrale tout en ignorant les consignes de sécurité imposées et en menaçant de renvoyer ses opérateurs, les tests en question seront à l'origine du plus gros accident nucléaire jamais connu.",
      "background__2": "https://i.goopics.net/dRXmd.png",
      "sentence__1": "Je me suis retrouvé confronté à un mensonge, un énorme mensonge qui a été répété à maintes reprises par les dirigeants de notre État.",
      "sentence__2": "Ces mensonges m’ont brisé. Je n’ai pas le moindre doute que les concepteurs du réacteur ont tout de suite trouvé la vraie cause de l’accident, mais qu’ils ont tout fait pour que les opérateurs se sentent coupables.",
      "background__3": "https://i.goopics.net/NvKL1.png",
      "sentence__6": "Je pensais que mes yeux sortaient de mes orbites. Il n’y avait aucun moyen de l’expliquer. Il était clair que ce n’était pas un accident normal, mais quelque chose de beaucoup plus terrible. C’était une catastrophe.",
      "sentence__7": "Il n’y avait vraiment plus rien à faire pour Dyatlov. Des pompiers professionnels de Tchernobyl et de Pripyat ont été appelés, et 27 d’entre eux ont été envoyés à l’hôpital cette nuit-là.",
      "sentence__8": "Leur courage et leur détermination ont aidé à maîtriser le feu à l’aube, mais personne ne portait de vêtements de protection cette nuit-là et les seuls dosimètres disponibles ne pouvaient même pas fournir une lecture précise des rayonnements qui s’échappaient.",
      "background__slider": "https://i.goopics.net/K8wm3.png",
      "image__slider": "https://i.goopics.net/8g5r7.png",
      "image__slider__2": "https://i.goopics.net/OKmW2.png",
      "image__slider__3": "https://i.goopics.net/0WXpO.png",
      "image__slider__4": "https://i.goopics.net/oAWGG.png",
      "image__slider__5": "https://i.goopics.net/2WZvR.png",
      "video__1": mp4.diatlov,
      "video__2": mp4.outroIgor
    },
  ]
 }
  
 